[package]
name = "suave"
version = "0.1.0"
edition = "2021"
authors = ["Deeton Rushton"]
description = "A networking layer for communication."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
